//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CCPrintUI.rc
//
#define IDS_SECTION                     1
#define IDS_AUTOOPEN                    1
#define IDS_CALIBRATED                  2
#define IDS_NAME                        3
#define IDS_LICENSELOCATION_TOP         4
#define IDS_LICENSELOCATION_BOTTOM      5
#define IDS_LICENSELOCATION_USER        6
#define IDS_DESCRIPTION_CC              14
#define IDS_DESCRIPTION_SAMPING         15
#define IDS_DESCRIPTION_PUBLIC          16
#define IDS_DESCRIPTION_DEVNATIONS      17
#define IDS_DESCRIPTION_NONE            18
#define IDS_DESCRIPTION_GENERAL         19
#define IDS_DESCRIPTION_CC2             20
#define IDS_DESCRIPTION_GENERAL2        25
#define IDS_DESCRIPTION_CC_BY_NC        26
#define IDS_DESCRIPTION_CC_BY_NC_SA     27
#define IDS_DESCRIPTION_CC_BY_NC_ND     28
#define IDS_DESCRIPTION_CC_BY           29
#define IDS_DESCRIPTION_CC_BY_SA        30
#define IDS_DESCRIPTION_CC_BY_ND        31
#define IDS_DESCRIPTION_SAMPLING_REGULAR 32
#define IDS_DESCRIPTION_SAMPLING_PLUS   33
#define IDS_DESCRIPTION_SAMPLING_PLUS_NC 34
#define IDS_DESCRIPTION_JURISDICTION_ADD 35
#define IDS_DESCRIPTION_PUBLIC_FINAL    36
#define IDS_DESCRIPTION_DEVNATIONS_FINAL 37
#define IDS_DESCRIPTION_NONE_FINAL      38
#define IDS_TITLE_LICENSE_TYPE          39
#define IDS_TITLE_LICENSE_USAGE         40
#define IDS_TITLE_LICENSE_MODIFICATION  41
#define IDS_TITLE_LICENSE_JURISDICTION  42
#define IDS_TITLE_LICENSE_SAMPLING      43
#define IDS_TITLE_LICENSE_SUMMERY       44
#define IDS_WARNING_USERCANCEL          45
#define IDS_ERROR_RETRIEVEDATA_JURISDICTION 46
#define IDS_ERROR_RETRIEVEDATA          47
#define IDS_WARNING_USERCANCEL_JURISDICTION 48
#define IDS_ERROR_RETRIEVEDATA_SHORT    49
#define IDS_ERROR_RETRIEVELICENSE       50
#define IDB_CC                          104
#define IDD_DEVICE_PROPPAGE             106
#define IDD_LICENSE_PAGE                106
#define IDD_DOC_PROPPAGE                107
#define IDD_PDF_PAGE                    107
#define IDPNG_SAMPLING                  110
#define IDPNG_SAMPLING_PLUS             111
#define IDPNG_SAMPLING_PLUS_NC          112
#define IDD_LICENSE_LOCATION            118
#define IDPNG_BY_NC                     120
#define IDPNG_BY_NC_SA                  121
#define IDPNG_BY_NC_ND                  122
#define IDPNG_BY                        123
#define IDPNG_BY_SA                     124
#define IDPNG_BY_ND                     125
#define IDPNG_SOMERIGHTS                128
#define IDI_ATTRIBUTION                 140
#define IDI_COMMERCIAL_NO               142
#define IDI_SHAREALIKE                  143
#define IDI_DERIVATIVE_NO               144
#define IDI_PUBLICDOMAIN                145
#define IDI_DEVELOPINGNATIONS           146
#define IDI_SAMPLING                    147
#define IDI_SAMPLING_PLUS               148
#define IDI_CC                          149
#define IDX_STANDARD                    150
#define IDX_RECOMBO                     151
#define IDX_CC_BY_NC                    152
#define IDX_CC_BY_NC_SA                 153
#define IDX_CC_BY_NC_ND                 154
#define IDX_CC_BY                       155
#define IDX_CC_BY_SA                    156
#define IDX_CC_BY_ND                    157
#define IDX_SAMPLING                    158
#define IDX_SAMPLING_PLUS               159
#define IDX_SAMPLING_PLUS_NC            160
#define IDD_PROGRESS                    201
#define IDD_LICENSEPAGE_JURISDICTION    202
#define IDD_LICENSEPAGE_TYPE            203
#define IDD_LICENSEPAGE_MODIFICATION    204
#define IDD_LICENSEPAGE_SAMPLING        205
#define IDD_LICENSEPAGE_SUMMERY         206
#define IDD_LICENSEPAGE_USAGE           207
#define IDC_CALIBRATE                   1001
#define IDC_FILENAME                    1002
#define IDC_BROWSE                      1003
#define IDC_DESCRIPTION                 1004
#define IDC_JURISDICTION                1005
#define IDC_LICENSE                     1006
#define IDC_SELECT_LICENSE              1007
#define IDC_LOCATION                    1008
#define IDC_AUTOOPEN                    1009
#define IDC_LICENSE_CC                  1010
#define IDC_FILENAME_LABEL              1011
#define IDC_LICENSE_SAMPLING            1011
#define IDC_PROGRESS                    1012
#define IDC_LICENSE_PD                  1012
#define IDC_LICENSE_DN                  1013
#define IDC_LICENSE_IMAGE               1013
#define IDC_LICENSE_NONE                1014
#define IDC_LICENSE_PROPERTIES          1014
#define IDC_STAMP                       1015
#define IDC_STAMP_ALL                   1017
#define IDC_LOCATION_SAME               1018
#define IDC_LOCATION_DIFFERENT          1019
#define IDC_LOCATION_OTHER              1020
#define IDC_LOCATION_USER               1021
#define IDC_LOCATION_OTHER_USER         1022
#define IDC_X                           1022
#define IDC_X2                          1023
#define IDC_Y                           1023
#define IDC_PLACEHOLDER                 1025
#define IDC_DERIVATIVE_ALL              1030
#define IDC_DERIVATIVE_SHARE            1031
#define IDC_DERIVATIVE_NO               1032
#define IDC_GENERAL                     1040
#define IDC_SPECIFIC                    1041
#define IDC_ICON1                       1042
#define IDC_ICON2                       1043
#define IDC_ICON3                       1044
#define IDC_COMMERICAL_YES              1045
#define IDC_COMMERICAL_NO               1046
#define IDC_SAMPLING                    1049
#define IDC_SAMPLING_PLUS               1050
#define IDC_SAMPLING_NC                 1051
#define IDC_NEXT                        1900
#define IDC_BACK                        1901

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
